[project]
name = "pgem"
version = "0.1.0"
description = "Offical code for PGEM by Emre Tekmen"
readme = "README.md"
requires-python = ">=3.10"
dependencies = ["pydantic==2.12.4"]

[build-system]
requires = ["uv_build >= 0.9.9, <0.10.0"]
build-backend = "uv_build"
